### PR TITLE
Azure disks describe + delete for reaper 

### PR DESCRIPTION
**Pull request by kenazk**

### CODE REVIEW

**Comment by kenazk** [comment]
@bradhe can you take a look?

**Comment by bradhe** [comment]
Is this PR duplicative (or a subset of) #28 ?

**Comment by kenazk** [comment]
This is for Azure Disks – the other (#28) is exclusively for Azure VMs.

**Comment by kenazk** [comment]
Oh wait. Looks like the other one also includes disks. Will close this one.

**Pull request closed without merging**
